# Generated by Django 5.1.6 on 2025-03-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='my_invite_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='My Invite Code'),
        ),
    ]
