# Generated by Django 5.1.6 on 2025-04-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('feedback_type', models.CharField(choices=[('tech', 'Техническая проблема'), ('complaint', 'Жалоба'), ('suggestion', 'Предложение'), ('question', 'Вопрос'), ('service', 'Сервис и обслуживание'), ('site', 'Ошибка на сайте'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип обращения')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
