# Generated by Django 5.1.6 on 2025-03-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='premium_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
