# Generated by Django 5.1.6 on 2025-04-07 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('offers', '0004_category_description_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='location.locality', verbose_name='Населённый пункт'),
        ),
        migrations.AddField(
            model_name='offer',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='location.region', verbose_name='Область'),
        ),
    ]
